const $=s=>document.querySelector(s), state=JSON.parse(localStorage.getItem('finaleState')||'{}');
state.tasks ??= {death:false, safe:false, family:false, assets:false, decision:false, tax:false, registry:false};
const save=()=>localStorage.setItem('finaleState',JSON.stringify(state));
const shell=(body)=>`<div class="page">${body}<div class="footer-note">Finale는 상속 절차를 정리하고 기한을 관리하기 위한 정보 도구입니다. 실제 사건의 상속순위·채무·유언·해외재산·세금 등은 사실관계에 따라 달라질 수 있으므로 법원·정부기관 또는 전문가 확인이 필요합니다. 기준 정보: 대한민국 법원, 정부24, 국세청 공개 안내(2026-09 확인).</div></div>`;
const home=()=>shell(`<section class="hero"><div><div class="eyebrow">상속, 복잡함 대신 순서대로</div><h1>남겨진 일을<br>하나씩 정리하세요.</h1><p>사망신고부터 재산조회, 상속방법 결정, 세금과 명의이전까지. Finale가 해야 할 일을 한 화면에서 정리해 드립니다.</p><div class="btns"><a class="btn primary" href="#guide">내 상속 절차 시작하기 →</a><a class="btn secondary" href="#docs">필요서류 보기</a></div></div><img src="assets/illustrations/family.svg" alt="가족 일러스트"></section>
<section class="section"><div class="sectionhead"><div><h2>지금 해야 할 일</h2><p>중요한 순서부터 확인하세요.</p></div><span class="badge">로컬 저장</span></div><div class="grid"><a class="card" href="#guide"><div class="ico">1</div><h3>상속 절차 확인</h3><p>사망 후 해야 할 일을 시간 순서대로 안내합니다.</p></a><a class="card" href="#assets"><div class="ico">⌕</div><h3>재산·채무 정리</h3><p>부동산, 금융, 자동차, 채무를 한 곳에 기록합니다.</p></a><a class="card" href="#docs"><div class="ico">▤</div><h3>필요서류</h3><p>절차별 기본 서류와 발급처를 확인합니다.</p></a><a class="card" href="#tasks"><div class="ico">✓</div><h3>진행상황</h3><p>완료한 업무를 체크하고 진행률을 확인합니다.</p></a></div></section>
<section class="section quick"><div class="card deadline"><small>중요 기한</small><h2>상속포기·한정승인</h2><strong>상속인이 된 사실을 안 날부터 3개월</strong><p>재산보다 채무가 많을 가능성이 있다면 재산을 임의 처분하기 전에 검토하세요.</p><a class="btn secondary" href="#decision">선택 도우미</a></div><div class="card"><h2>내 진행률</h2><p>${doneCount()} / 7 단계 완료</p><div class="progress"><i style="width:${doneCount()/7*100}%"></i></div><div class="list" style="margin-top:18px">${miniTask('사망신고','death')}${miniTask('안심상속 재산조회','safe')}${miniTask('상속방법 결정','decision')}</div></div></section>`);
function doneCount(){return Object.values(state.tasks).filter(Boolean).length} function miniTask(t,k){return `<div class="row"><span>${state.tasks[k]?'●':'○'}</span><div class="grow">${t}</div><span class="badge ${state.tasks[k]?'green':''}">${state.tasks[k]?'완료':'대기'}</span></div>`}
const guide=()=>shell(`<div class="titleblock"><img src="assets/illustrations/family.svg"><div><h1>상속 절차 가이드</h1><p>일반적인 국내 상속의 흐름을 단계별로 정리했습니다.</p></div></div><div class="notice">채무가 불명확하면 상속재산을 임의로 처분하기 전에 한정승인·상속포기 가능성을 먼저 검토하세요. 사건별 기산점과 법률효과는 달라질 수 있습니다.</div><section class="section steps">${step(1,'사망 관련 행정','사망신고 및 가족관계 서류를 준비합니다.','death')}${step(2,'상속인 확인','가족관계증명서 등을 통해 상속관계를 확인합니다.','family')}${step(3,'재산조회','안심상속 등으로 금융·토지·자동차·세금 등을 조회합니다.','safe')}${step(4,'재산·채무 확정','조회 결과와 별도 재산·채무를 목록화합니다.','assets')}${step(5,'상속방법 결정','단순승인·한정승인·상속포기를 검토합니다.','decision')}${step(6,'세금 신고 검토','상속세 납부의무와 신고기한을 확인합니다.','tax')}${step(7,'명의이전·정리','부동산·금융·자동차 등 후속 이전을 진행합니다.','registry')}</section><div class="btns"><a class="btn primary" href="#tasks">체크리스트로 진행하기</a><a class="btn secondary" href="#decision">상속방법 비교</a></div></section>`);
function step(n,t,d,k){return `<div class="card"><div class="stepnum">${n}</div><h3>${t}</h3><p>${d}</p><span class="badge ${state.tasks[k]?'green':''}">${state.tasks[k]?'완료':'확인 필요'}</span></div>`}
const assets=()=>shell(`<div class="titleblock"><img src="assets/illustrations/assets.svg"><div><h1>상속재산 정리</h1><p>재산과 채무를 직접 기록해 순재산을 가늠합니다.</p></div></div><div class="grid"><div class="card"><div class="ico">⌂</div><h3>부동산</h3><p>토지·건물·분양권 등</p></div><div class="card"><div class="ico">₩</div><h3>금융재산</h3><p>예금·보험·증권 등</p></div><div class="card"><div class="ico">▱</div><h3>자동차·기타</h3><p>차량·회원권·사업재산 등</p></div><div class="card"><div class="ico">−</div><h3>채무</h3><p>대출·보증·세금·미납금 등</p></div></div><section class="section card"><h2>간단 재산 계산기</h2><div class="formgrid"><div class="field"><label>적극재산 합계(원)</label><input id="positive" inputmode="numeric" value="${state.positive||''}" placeholder="예: 300000000"></div><div class="field"><label>채무 합계(원)</label><input id="debt" inputmode="numeric" value="${state.debt||''}" placeholder="예: 120000000"></div></div><div class="calcbox" id="netbox">금액을 입력하면 순재산을 계산합니다.</div></section><section class="section card"><h2>안심상속 원스톱서비스</h2><p>금융내역·토지·자동차·세금·연금가입유무 등을 통합 조회할 수 있습니다. 온라인과 방문 신청의 자격 범위가 다를 수 있습니다.</p><a class="btn primary" target="_blank" rel="noopener" href="https://www.gov.kr/mw/AA020InfoCappView.do?CappBizCD=17400000001">정부24 공식 안내 열기 ↗</a></section>`);
const docs=()=>shell(`<div class="titleblock"><img src="assets/illustrations/docs.svg"><div><h1>필요서류</h1><p>어떤 단계에서 무엇을 확인해야 하는지 정리했습니다.</p></div></div><div class="list">${doc('상속관계 확인','가족관계증명서(상세), 기본증명서 등','전자가족관계등록시스템 / 주민센터')}${doc('안심상속 재산조회','신분증, 상속관계 증빙서류 등','정부24 / 시·구청 / 읍·면·동')}${doc('상속포기·한정승인','심판청구서와 사건별 첨부서류','피상속인 최후주소지 관할 가정법원')}${doc('상속세 신고','상속세 신고서, 재산·채무·공제 관련 명세 등','홈택스 / 관할 세무서')}${doc('부동산 상속등기','상속관계·등기원인 관련 서류 등','등기소 / 인터넷등기소 안내 확인')}</div><div class="notice" style="margin-top:18px">실제 제출서류는 가족관계, 유언, 협의분할, 미성년 상속인, 해외거주 여부 등에 따라 달라질 수 있습니다. 제출 전 담당기관의 최신 안내를 확인하세요.</div>`);
function doc(t,d,w){return `<div class="row"><div class="ico">▤</div><div class="grow"><b>${t}</b><div><small>${d}</small></div></div><span class="badge">${w}</span></div>`}
const tasks=()=>shell(`<div class="titleblock"><img src="assets/illustrations/empty.svg"><div><h1>진행상황</h1><p>체크 내용은 이 기기의 브라우저에 저장됩니다.</p></div></div><div class="card"><div class="sectionhead"><div><h2>${doneCount()} / 7 완료</h2><p>전체 상속 절차 진행률</p></div><b>${Math.round(doneCount()/7*100)}%</b></div><div class="progress"><i style="width:${doneCount()/7*100}%"></i></div><div class="list" style="margin-top:20px">${task('death','사망 관련 행정 확인','사망신고 및 초기 행정 절차')}${task('family','상속인 관계 확인','가족관계 서류로 상속관계 점검')}${task('safe','안심상속 재산조회 신청','통합 재산조회 신청 여부')}${task('assets','재산·채무 목록 작성','조회 외 재산과 채무까지 목록화')}${task('decision','상속방법 결정','단순승인·한정승인·포기 검토')}${task('tax','상속세 신고 여부 확인','신고·납부의무 및 기한 검토')}${task('registry','명의이전·후속 정리','부동산·금융·자동차 등')}</div><div class="btns"><button class="btn secondary" id="resetBtn">진행상황 초기화</button></div></div>`);
function task(k,t,d){return `<label class="row task"><input type="checkbox" data-task="${k}" ${state.tasks[k]?'checked':''}><div class="grow"><b>${t}</b><div><small>${d}</small></div></div></label>`}
const decision=()=>shell(`<div class="titleblock"><img src="assets/illustrations/docs.svg"><div><h1>상속방법 비교</h1><p>결정 자체가 아닌, 선택지를 이해하기 위한 안내입니다.</p></div></div><div class="grid" style="grid-template-columns:repeat(3,1fr)"><div class="card"><div class="ico">✓</div><h3>단순승인</h3><p>상속재산과 채무를 제한 없이 승계하는 방식입니다. 일정한 행위나 기간 경과로 단순승인으로 간주될 수 있습니다.</p></div><div class="card"><div class="ico">◐</div><h3>한정승인</h3><p>상속으로 취득할 재산의 한도에서 피상속인의 채무와 유증을 변제하는 조건으로 승인하는 방식입니다.</p></div><div class="card"><div class="ico">×</div><h3>상속포기</h3><p>상속의 효력을 거부하는 절차입니다. 후순위 상속인에게 영향이 이어질 수 있어 가족 전체의 상속순위를 함께 살펴야 합니다.</p></div></div><section class="section card"><h2>중요한 3개월</h2><p>대한민국 법원 안내에 따르면 상속포기 또는 한정승인은 원칙적으로 상속개시 있음을 안 날부터 3개월 내 관할 가정법원에 청구합니다.</p><div class="notice">채무 초과 사실을 뒤늦게 알게 된 경우의 특별한정승인 등 예외가 존재합니다. 구체적 사건은 법률전문가 또는 관할 법원에 확인하세요.</div></section>`);
const routes={home,guide,assets,docs,tasks,decision};
function render(){const key=location.hash.slice(1)||'home'; $('#view').innerHTML=(routes[key]||home)(); bind(); scrollTo(0,0)}
function bind(){document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{state.tasks[x.dataset.task]=x.checked;save();render()}); const r=$('#resetBtn');if(r)r.onclick=()=>{Object.keys(state.tasks).forEach(k=>state.tasks[k]=false);save();render()}; const p=$('#positive'),d=$('#debt');if(p&&d){const calc=()=>{state.positive=p.value.replace(/\D/g,'');state.debt=d.value.replace(/\D/g,'');save();const n=(+state.positive||0)-(+state.debt||0);$('#netbox').innerHTML=`추정 순재산 <b>${n.toLocaleString()}원</b> ${n<0?'<span class="badge red">채무 초과 가능성</span>':'<span class="badge green">적극재산 우위</span>'}`};p.oninput=d.oninput=calc;calc()}}
$('#themeBtn').onclick=()=>document.body.classList.toggle('dark'); addEventListener('hashchange',render);render();
